### ISSUE TITLE
 Issue with BoratRAT Sample Link in the Code

### ISSUE THREAD

**Issue by dnwawl** [dtrizna/quo.vadis#4]
Hello dtrizna,

I hope you're doing well. I was going through your code and noticed that the link provided for the BoratRAT sample from VX-UNDERGROUND seems to be broken or not accessible:
https://samples.vx-underground.org/samples/Families/BoratRAT/Samples/b47c77d237243747a51dd02d836444ba067cf6cc4b8b3344e5cf791f5f41d20e.7z
I tried accessing it multiple times, but without success. I believe this could be an oversight, or the sample might have been moved or removed from the source.

It would be greatly appreciated if you could check on this and possibly provide an updated link or suggest an alternative source for the sample. This will be very helpful for those of us who are trying to follow along with your work.

Thank you for your attention to this matter and for your contributions to the community. Looking forward to your response.

Best regards

**Comment by dtrizna** [comment]
Just open the VX site and browse samples. VX site changed slightly the URL of how they host samples, but it is still there, and easily findable:

https://www.vx-underground.org/#E:/root/Samples/Families/BoratRAT/Samples

https://samples.vx-underground.org/root/Samples/Families/BoratRAT/Samples/b47c77d237243747a51dd02d836444ba067cf6cc4b8b3344e5cf791f5f41d20e.7z
